### ISSUE TITLE
Statement not an instance of ForwardCompatibility\Result

### ISSUE THREAD

**Issue by wizhippo** [doctrine/dbal#4572]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13

#### Summary

This is odd, after update to 2.13 I am getting

```
  Argument 1 passed to eZ\Bundle\EzPublishCoreBundle\Command\ReindexCommand::fetchIteration() must implement interface Doctrine\DBAL\Driver\Statement, instance of Doctrine\DBAL\ForwardCompatibility\Result given, called in /var/www/vendor/ezsystems/ezplatform-kernel/eZ/Bundle/Ez  
  PublishCoreBundle/Command/ReindexCommand.php on line 308              
```                                                                      
             
ReindexCommand::fetchIteration()  is defined as function fetchIteration(Doctrine\DBAL\Driver\Statement $stmt, $iterationCount)
Statement extends Doctrine\DBAL\Driver\ResultStatement
ForwardCompatibility\Result implements Doctrine\DBAL\Driver\ResultStatement 

Why is this thrown if ForwardCompatibility\Result implements  ResultStatement and Statement extends ResultStatement?

**Comment by beberlei** [comment]
@wizhippo confusing indeed

**Comment by snapshotpl** [comment]
Same here

**Comment by beberlei** [comment]
Ok, you are typehinting for `Driver\Statement` and `ForwardCompatibility\Result` does not implement that. I am afraid this is a BC break that we introduced in Doctrine DBAL 2.9 in 2018 when we changed the docblock return value for `executeQuery` to `ResultStatement`. See https://github.com/doctrine/dbal/pull/3025/files#diff-425f50e688c77962b97e5fd1f9803a6d9ffa9bf260ba12391f73b2aab14914eeR911

It is not something we can fix anymore, you need to change your code and typehint for `ResultStatement` or disallow DBAL 2.13 for now.

However `ResultStatement` is also deprecated, in another next step you need to move to using `Result`.

**Comment by snapshotpl** [comment]
@beberlei My mistake. My exception looks similar but looks like not depends on my code, but only internal Doctrine codebase:

```
Argument 1 passed to Doctrine\ORM\Internal\Hydration\AbstractHydrator::toIterable() must implement interface Doctrine\DBAL\Driver\Statement, instance of Doctrine\DBAL\ForwardCompatibility\Result given, called in /app/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php on line 1010
```

If I'm right, I can open new issue

**Comment by snapshotpl** [comment]
Ok, looks like fixed now :) https://github.com/doctrine/orm/issues/8575
